pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=gbogard"
      - "title~=Update .* to .*"
    actions:
      merge:
        strict: smart
        strict_method: merge
